# Generated by Django 4.2.4 on 2023-08-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='vidpost',
        ),
    ]
