# Generated by Django 4.2.4 on 2023-08-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptest', '0003_rename_post_like_vidpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='PicLike',
        ),
        migrations.RemoveField(
            model_name='piclike',
            name='vidpost',
        ),
        migrations.AddField(
            model_name='piclike',
            name='picpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apptest.image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VidLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vidpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.video')),
            ],
        ),
    ]
