# Generated by Django 4.2.4 on 2023-08-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0005_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piclike',
            name='likes',
        ),
    ]
