# Generated by Django 4.2.4 on 2023-08-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0006_remove_piclike_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidlike',
            name='likes',
        ),
    ]
