# Generated by Django 4.2.4 on 2023-09-03 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptest', '0007_remove_vidlike_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='SaveImage',
        ),
        migrations.CreateModel(
            name='SaveVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.video')),
            ],
        ),
    ]
